name: Asciidoc rendering CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Render the PDF with an asciidoc builder
      run: |
        docker run \
        -v ${{ github.workspace }}:/workspace/ \
        --name asciidoc-to-pdf \
        heckj/docker-asciidoctor \
        asciidoctor-pdf -v -t -D /workspace/output /workspace/docs/uyc-book.adoc
    - name: list workspace...
      run: |
        docker run \
        -v ${{ github.workspace }}:/workspace/ \
        heckj/docker-asciidoctor \
        /bin/sh -c "ls -altr /workspace/output"
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: pdf
        path: workspace/output/*.pdf
